homeassistant:
  name: Casa
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 30
  unit_system: metric
  time_zone: America/Sao_Paulo
  customize: !include customize.yaml

zone:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  icon: mdi:home
  radius: 18
zone 2:
  name: Trabalho
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  icon: mdi:home-modern
  radius: 18

config:
conversation:
hassio:
history:
ios:
logbook:
map:
sun:
updater:
zeroconf:

alarm_control_panel: !include alarm.yaml
automation: !include automation.yaml
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
climate: !include climate.yaml
cover: !include cover.yaml
device_tracker: !include device_tracker.yaml
frontend: !include frontend.yaml
group: !include group.yaml
http: !include http.yaml
input_boolean: !include input_boolean.yaml
light: !include light.yaml
logger: !include logger.yaml
media_player: !include media_player.yaml
mqtt: !include mqtt.yaml
notify: !include notify.yaml
recorder: !include recorder.yaml
scene: !include scene.yaml
script: !include script.yaml
sensor: !include sensor.yaml
shell_command: !include shell_command.yaml
switch: !include switch.yaml
tts: !include tts.yaml
xiaomi_aqara: !include xiaomi_aqara.yaml