homeassistant:
  name: Casa
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 30
  unit_system: metric
  time_zone: America/Sao_Paulo
  customize: !include includes/customize.yaml
  packages: !include_dir_named includes/packages/
  auth_providers: !include includes/auth_providers.yaml

zone:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  icon: mdi:home
  radius: 18
zone 2:
  name: Trabalho
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  icon: mdi:home-modern
  radius: 18

api:
config:
conversation:
ffmpeg:
hassio:
history:
logbook:
map:
#stream:
sun:
system_health:
updater:
wake_on_lan:
zeroconf:

alarm_control_panel: !include includes/alarm.yaml
asuswrt: !include includes/asuswrt.yaml
automation: !include includes/automation.yaml
binary_sensor: !include includes/binary_sensor.yaml
camera: !include includes/camera.yaml
climate: !include includes/climate.yaml
cover: !include includes/cover.yaml
device_tracker: !include includes/device_tracker.yaml
#discovery: !include includes/discovery.yaml
fastdotcom: !include includes/fastdotcom.yaml
frontend: !include includes/frontend.yaml
google_assistant: !include includes/google_assistant.yaml
googlehome: !include includes/googlehome.yaml
group: !include includes/group.yaml
homekit: !include includes/homekit.yaml
http: !include includes/http.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
input_select: !include includes/input_select.yaml
ios: !include includes/ios.yaml
light: !include includes/light.yaml
logger: !include includes/logger.yaml
media_player: !include includes/media_player.yaml
mqtt: !include includes/mqtt.yaml
notify: !include includes/notify.yaml
octoprint: !include includes/octoprint.yaml
panel_iframe: !include includes/panel_iframe.yaml
person: !include includes/person.yaml
recorder: !include includes/recorder.yaml
rest_command: !include includes/rest_command.yaml
scene: !include includes/scene.yaml
script: !include includes/script.yaml
sensor: !include includes/sensor.yaml
shell_command: !include includes/shell_command.yaml
smartir: !include includes/smartir.yaml
#spotcast: !include includes/spotcast.yaml
switch: !include includes/switch.yaml
timer: !include includes/timer.yaml
tts: !include includes/tts.yaml
tuya: !include includes/tuya.yaml
vacuum: !include includes/vacuum.yaml
weather: !include includes/weather.yaml
xiaomi_aqara: !include includes/xiaomi_aqara.yaml