homeassistant:
  name: Casa
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 30
  unit_system: metric
  time_zone: America/Sao_Paulo
  customize: !include includes/customize.yaml
  packages: !include_dir_named includes/packages/

zone:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  icon: mdi:home
  radius: 18
zone 2:
  name: Trabalho
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  icon: mdi:home-modern
  radius: 18

config:
conversation:
discovery:
ffmpeg:
hassio:
history:
logbook:
map:
sun:
updater:
zeroconf:

alarm_control_panel: !include includes/alarm.yaml
automation: !include includes/automation.yaml
binary_sensor: !include includes/binary_sensor.yaml
camera: !include includes/camera.yaml
cast: !include includes/cast.yaml
cloud: !include includes/cloud.yaml
climate: !include includes/climate.yaml
cover: !include includes/cover.yaml
device_tracker: !include includes/device_tracker.yaml
frontend: !include includes/frontend.yaml
#google_assistant: includes/google_assistant.yaml
group: !include includes/group.yaml
homekit: !include includes/homekit.yaml
http: !include includes/http.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
input_select: !include includes/input_select.yaml
ios: !include includes/ios.yaml
light: !include includes/light.yaml
logger: !include includes/logger.yaml
media_player: !include includes/media_player.yaml
mqtt: !include includes/mqtt.yaml
notify: !include includes/notify.yaml
recorder: !include includes/recorder.yaml
scene: !include includes/scene.yaml
script: !include includes/script.yaml
sensor: !include includes/sensor.yaml
shell_command: !include includes/shell_command.yaml
switch: !include includes/switch.yaml
tts: !include includes/tts.yaml
#upnp: !include includes/upnp.yaml
vacuum: !include includes/vacuum.yaml
weather: !include includes/weather.yaml
xiaomi_aqara: !include includes/xiaomi_aqara.yaml