- platform: webostv
  host: 192.168.1.39
  mac: 3C:CD:93:19:74:3D
  name: "TV Sala"
  filename: webostv2.conf
  customize:
    sources:
      - livetv
      - youtube
      - netflix
- platform: webostv
  host: 192.168.1.38
  mac: 3C:CD:93:85:F0:2F
  name: "TV Suíte"
  filename: webostv1.conf
  customize:
    sources:
      - livetv
      - youtube
      - netflix
- platform: cast
  host: 192.168.1.71