automation:

  - alias: Botões Sonoff MQTT
    initial_state: true
    trigger:
      platform: mqtt
      topic: stat/+/BUTTON
    condition:
      condition: template
      value_template: >
        {% set topic = trigger.topic.split('/')[1] | lower %}
        {% set button = trigger.payload_json.BUTTON | lower %}
        {% set action = trigger.payload_json.ACTION | lower %}
        {% set object_id = 'sonoff_botao_{}_{}_{}'.format(topic, button, action) %}
        {{ states.script[object_id] != None }}
    action:
      - service_template: script.sonoff_botao_{{ trigger.topic.split('/')[1] | lower }}_{{ trigger.payload_json.BUTTON | lower }}_{{ trigger.payload_json.ACTION | lower }}

  - alias: Botões Sonoff EspHome
    initial_state: true
    trigger:
      - platform: state
        from: 'button_pressed'
        entity_id:
          - sensor.banheiro_203_interruptores
          - sensor.cafeteira_interruptores
          - sensor.cafeteira_muvrh_interruptores
          - sensor.casa_sonoff_testes_interruptores
          - sensor.chaleira_interruptores
          - sensor.ender3_interruptores
          - sensor.entrada_203_interruptores
          - sensor.entrada_303_interruptores
          - sensor.mesa_de_jantar_interruptores
    condition:
      condition: template
      value_template: >
        {% set entity = trigger.to_state.entity_id.split('.')[1] | lower %}
        {% set topic = entity.replace('_interruptores','') | lower %}
        {% set dump, number, action = trigger.to_state.state.split('_') %}
        {% set object_id = 'sonoff_botao_{}_{}_{}'.format(topic, number, action) %}
        {{ states.script[object_id] != None }}
    action:
      - service_template: >
          {% set entity = trigger.to_state.entity_id.split('.')[1] | lower %}
          {% set topic = entity.replace('_interruptores','') | lower %}
          {% set dump, number, action = trigger.to_state.state.split('_') %}
          {% set object_id = 'sonoff_botao_{}_{}_{}'.format(topic, number, action) %}
          script.sonoff_botao_{{ topic }}_{{ number }}_{{ action }}

script:

## Casa

  sonoff_botao_cafeteira_01_long:
    alias: "Botão Sonoff - Luz principal"
    sequence:
      - service: light.toggle
        entity_id: light.cozinha

  sonoff_botao_chaleira_01_long:
    alias: "Botão Sonoff - Luz balcão"
    sequence:
      - service: light.toggle
        entity_id: light.ledcozinhabalcao

  sonoff_botao_ender3_00_long:
    alias: "Botão Sonoff - Preaquecer cama"
    sequence:
      - service: switch.turn_on
        entity_id: switch.ender3
      - wait_template: "{{is_state('switch.conectar_octoprint', 'on')}}"
        timeout: 00:01:00
        continue_on_timeout: false
      - service: script.octoprint_preheat_bed

  sonoff_botao_ender3_00_double:
    alias: "Botão Sonoff - teste 01"
    sequence:
      - service: light.toggle
        entity_id: light.mesa_de_jantar

  sonoff_botao_ender3_00_triple:
    alias: "Botão Sonoff - teste 02"
    sequence:
      - service: light.toggle
        entity_id: light.luz_principal_da_sala

## MuvRH

  sonoff_botao_entrada_303_01_long:
    alias: "Botão Sonoff - Desligar/ligar tudo na sala 303"
    sequence:
      - service_template: >-
          {% if is_state('group.muvrh_tudo_sala_303', 'off') %}
            homeassistant.turn_on
          {% else %}
            homeassistant.turn_off
          {% endif %}
        data_template:
          entity_id: >-
            {% if is_state('group.muvrh_tudo_sala_303', 'off') %}
              group.muvrh_tudo_sala_303
            {% else %}
              group.muvrh_tudo_sala_303
            {% endif %}

  sonoff_botao_cafeteira_muvrh_00_long:
    alias: "Botão Sonoff - Cafeteira liga luz nossa sala"
    sequence:
      - service: light.toggle
        entity_id: light.muv203nossasala
