timer:

  lava_loucas:
    name: "Tempo restante"
    icon: mdi:camera-timer

input_select:

  lava_loucas_casa_modo_lavagem:
    name: "Modo de lavagem"
    options:
      - "Selecionar"
      - "Aquaspray"
      - "Econômico"
      - "Dia a dia"
    initial: "Selecionar"
    icon: mdi:format-list-checks

binary_sensor:

  - platform: template
    sensors:
      lava_loucas_casa:
        friendly_name: "Lava-louças"
        device_class: "power"
        value_template: "{{ not is_state('input_select.lava_loucas_casa_modo_lavagem', 'Selecionar') }}"
        entity_id: input_select.lava_loucas_casa_modo_lavagem

switch:

  - platform: template
    switches:
      lava_loucas_homekit_aquaspray:
        friendly_name: "Lava-louças aquaspray"
        value_template: "{{ is_state('input_select.lava_loucas_casa_modo_lavagem', 'Aquaspray') }}"
        entity_id: input_select.lava_loucas_casa_modo_lavagem
        turn_on:
          service: input_select.select_option
          entity_id: input_select.lava_loucas_casa_modo_lavagem
          data_template:
            option: "Aquaspray"
        turn_off:
          service: script.lava_loucas_casa_iniciar_parar
        icon_template: mdi:dishwasher

      lava_loucas_homekit_economico:
        friendly_name: "Lava-louças econômico"
        value_template: "{{ is_state('input_select.lava_loucas_casa_modo_lavagem', 'Econômico') }}"
        entity_id: input_select.lava_loucas_casa_modo_lavagem
        turn_on:
          service: input_select.select_option
          entity_id: input_select.lava_loucas_casa_modo_lavagem
          data_template:
            option: "Econômico"
        turn_off:
          service: script.lava_loucas_casa_iniciar_parar
        icon_template: mdi:dishwasher

      lava_loucas_homekit_diaadia:
        friendly_name: "Lava-louças dia a dia"
        value_template: "{{ is_state('input_select.lava_loucas_casa_modo_lavagem', 'Dia a dia') }}"
        entity_id: input_select.lava_loucas_casa_modo_lavagem
        turn_on:
          service: input_select.select_option
          entity_id: input_select.lava_loucas_casa_modo_lavagem
          data_template:
            option: "Dia a dia"
        turn_off:
          service: script.lava_loucas_casa_iniciar_parar
        icon_template: mdi:dishwasher

automation:

  - alias: Lava-louças - Iniciar lavagem
    initial_state: true
    trigger:
      platform: state
      entity_id: input_select.lava_loucas_casa_modo_lavagem
    action:
      - service_template: >-
          {%- if is_state('input_select.lava_loucas_casa_modo_lavagem', 'Aquaspray') and is_state('input_boolean.lava_loucas_sujo' , 'on')%}
              script.lava_loucas_casa_aquaspray
          {%- elif is_state('input_select.lava_loucas_casa_modo_lavagem', 'Aquaspray') and is_state('input_boolean.lava_loucas_sujo' , 'off')%}
              script.lava_loucas_casa_aquaspray_louca_limpa
          {%- elif is_state('input_select.lava_loucas_casa_modo_lavagem', 'Econômico') %}
              script.lava_loucas_casa_iniciar_modo_economico
          {%- elif is_state('input_select.lava_loucas_casa_modo_lavagem', 'Dia a dia') %}
              script.lava_loucas_casa_modo_diaadia
          {%- else %}
              script.nada
          {%- endif %}

  - alias: Lava-louças - Ligar luz status máquina lava-louças
    initial_state: true
    hide_entity: True
    trigger:
      platform: state
      entity_id: group.movimento_luz_status_lava_loucas
      to: 'on'
    condition:
      condition: state
      entity_id: light.status_maquina_de_lavar_loucas
      state: 'off'
    action:
      - service: light.turn_on
        entity_id: light.status_maquina_de_lavar_loucas
        data_template:
          transition: 3
          brightness_pct: 100
          effect: >-
            {%- if is_state('binary_sensor.lava_loucas_casa' , 'on') %}
              ProgressBar
            {%- elif is_state('input_boolean.lava_loucas_sujo' , 'on') %}
              Piscar vermelho
            {%- else %}
              Piscar verde
            {%- endif %}

  - alias: Lava-louças - Desligar luz status máquina lava-louças
    initial_state: true
    hide_entity: True
    trigger:
      platform: state
      entity_id: light.status_maquina_de_lavar_loucas
      to: 'on'
    action:
      - wait_template: "{{ ((is_state('light.status_maquina_de_lavar_loucas' , 'off')) or ((as_timestamp(strptime(states.sensor.date_time.state, '%Y-%m-%d, %H:%M')) - ((as_timestamp(states.light.status_maquina_de_lavar_loucas.last_updated) ) / 60) | int) >= 5)) and is_state('group.movimento_luz_status_lava_loucas' , 'off') and is_state('binary_sensor.lava_loucas_casa' , 'off') }}"
      - condition: state
        entity_id: light.status_maquina_de_lavar_loucas
        state: 'on'
      - service: light.turn_off
        entity_id: light.status_maquina_de_lavar_loucas

  - alias: Lava-louças - Alerta louça suja
    initial_state: true
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_boolean.lava_loucas_sujo
      from: "off"
      to: "on"
    action:
      - service: script.ghm_tts
        data_template:
          tts: <speak><amazon:auto-breaths frequency='medium'>Ok, vou programar as limpezas automáticas.</amazon:auto-breaths></speak>
          volume: 0.5
      - service: light.turn_on
        data:
          entity_id: light.status_maquina_de_lavar_loucas
          transition: 3
          rgb_color: [255,0,0]
          brightness_pct: 100
          effect: 'Scan'
      - delay: '00:00:05'
      - wait_template: "{{ is_state('binary_sensor.porta_lava_loucas', 'off') }}"
      - service: light.turn_on
        entity_id: light.status_maquina_de_lavar_loucas
        data:
          transition: 3
          brightness_pct: 100
          effect: Piscar vermelho

  - alias: Lava-louças - Desligar luz ao reiniciar
    initial_state: true
    hide_entity: True
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: light.turn_off
        entity_id: light.status_maquina_de_lavar_loucas

  - alias: Lava-louças - Aquaspray automático
    initial_state: true
    trigger:
      - platform: time
        at: '02:00:00'
      - platform: time
        at: '10:00:00'
      - platform: time
        at: '14:00:00'
    condition:
      condition: state
      entity_id: input_boolean.lava_loucas_sujo
      state: 'on'
    action:
      - wait_template: "{{ is_state('binary_sensor.lava_loucas_casa' , 'off') }}"
      - delay: '00:00:10'
      - condition: state
        entity_id: input_boolean.lava_loucas_sujo
        state: 'on'
      - condition: state
        entity_id: binary_sensor.porta_lava_loucas
        state: 'off'
      - service: input_select.select_option
        entity_id: input_select.lava_loucas_casa_modo_lavagem
        data:
          option: "Aquaspray"
      - service: persistent_notification.create
        data:
          title: " Lava-louças ({{now().strftime('%H:%M')}})"
          message: "Aquaspray iniciado."

script:

  lava_loucas_casa_aquaspray_louca_limpa:
    alias: "Aquaspray com louça limpa"
    sequence:
    - service: input_select.select_option
      entity_id: input_select.lava_loucas_casa_modo_lavagem
      data:
        option: "Selecionar"
    - service: script.ghm_tts
      data_template:
        tts: <speak><amazon:auto-breaths frequency='medium'>A louça já está limpa, por favor descarregar antes de iniciar outra lavagem.</amazon:auto-breaths></speak>
        volume: 0.5

  lava_loucas_casa_aquaspray:
    alias: "Aquaspray"
    sequence:
    - service: light.turn_on
      data:
        entity_id: light.status_maquina_de_lavar_loucas
        transition: 3
        brightness_pct: 100
        effect: 'ProgressBar'
    - wait_template: "{{ is_state('binary_sensor.porta_lava_loucas', 'off') }}"
    - service: switch.turn_on
      entity_id: switch.lava_loucas_modo_aquaspray
    - service: timer.start
      data:
        entity_id: timer.lava_loucas
        duration: 00:06:05
    - wait_template: "{{ is_state('timer.lava_loucas', 'idle') }}"
    - service: input_boolean.turn_on
      entity_id: input_boolean.lava_loucas_sujo
    - service: input_select.select_option
      entity_id: input_select.lava_loucas_casa_modo_lavagem
      data:
        option: "Selecionar"
    - service: light.turn_on
      data:
        entity_id: light.status_maquina_de_lavar_loucas
        transition: 3
        brightness_pct: 100
        effect: 'Piscar vermelho'

  lava_loucas_casa_iniciar_modo_economico:
    alias: "Modo econômico"
    sequence:
    - service: light.turn_on
      data:
        entity_id: light.status_maquina_de_lavar_loucas
        transition: 3
        brightness_pct: 100
        effect: 'ProgressBar'
    - wait_template: "{{ is_state('binary_sensor.porta_lava_loucas', 'off') }}"
    - service: switch.turn_on
      entity_id: switch.lava_loucas_modo_economico
    - service: timer.start
      data:
        entity_id: timer.lava_loucas
        duration: 01:25:00
    - wait_template: "{{ is_state('timer.lava_loucas', 'idle') }}"
    - service: input_boolean.turn_off
      entity_id: input_boolean.lava_loucas_sujo
    - service: script.lava_loucas_casa_alerta_final
    - service: light.turn_on
      data:
        entity_id: light.status_maquina_de_lavar_loucas
        transition: 3
        brightness_pct: 100
        effect: 'Piscar verde'

  lava_loucas_casa_modo_diaadia:
    alias: "Modo dia a dia"
    sequence:
    - service: light.turn_on
      data:
        entity_id: light.status_maquina_de_lavar_loucas
        transition: 3
        brightness_pct: 100
        effect: 'ProgressBar'
    - wait_template: "{{ is_state('binary_sensor.porta_lava_loucas', 'off') }}"
    - service: switch.turn_on
      entity_id: switch.lava_loucas_modo_dia_a_dia
    - service: timer.start
      data:
        entity_id: timer.lava_loucas
        duration: 02:26:00
    - wait_template: "{{ is_state('timer.lava_loucas', 'idle') }}"
    - service: input_boolean.turn_off
      entity_id: input_boolean.lava_loucas_sujo
    - service: script.lava_loucas_casa_alerta_final
    - service: light.turn_on
      data:
        entity_id: light.status_maquina_de_lavar_loucas
        transition: 3
        brightness_pct: 100
        effect: 'Piscar verde'

  lava_loucas_casa_iniciar_parar:
    alias: "Iniciar/parar lavagem"
    sequence:
    - service: switch.turn_on
      entity_id: switch.lava_loucas_power
    - service: timer.cancel
      data:
        entity_id: timer.lava_loucas

  lava_loucas_casa_alterar_modo:
    alias: "Alterar modo de lavagem"
    sequence:
    - service: switch.turn_on
      entity_id: switch.lava_loucas_modo

  lava_loucas_casa_alerta_final:
    alias: "Alerta final"
    sequence:
    - service: input_select.select_option
      entity_id: input_select.lava_loucas_casa_modo_lavagem
      data:
        option: "Selecionar"
    - service: notify.tudo
      data_template:
        title: "Alerta Casa"
        message: "A lava-louças finalizou a lavagem."
    - service: persistent_notification.create
      data:
        title: "Alerta Casa ({{now().strftime('%H:%M')}})"
        message: "A lava-louças finalizou a lavagem."
    - service: script.ghm_tts
      data_template:
        tts: <speak><amazon:auto-breaths frequency='medium'>A lava-louças finalizou a lavagem, sugiro deixar a porta aberta para evitar odores indesejados.</amazon:auto-breaths></speak>
        volume: 0.5

homeassistant:
  customize:

    script.lava_loucas_casa_alterar_modo:
      icon: mdi:dishwasher

sensor:

  - platform: template
    sensors:
      lava_loucas_percentil_timer:
        unit_of_measurement: '%'
        friendly_name: 'Progresso da lavagem'
        entity_id: sensor.time
        value_template: >
          {% set timer = 'lava_loucas' %}
          {% if is_state('timer.'~timer,'active') %}
            {% set state = states.timer[timer] %}
            {% set dur = state.attributes.duration.split(':') %}
            {% set dur = ((dur[0]|int)*60+dur[1]|int)*60+dur[2]|int %}
            {{ ((now() - state.last_changed).total_seconds()/dur*100)|int }}
          {% else %}
            0
          {% endif %}

input_boolean:

  lava_loucas_sujo:
    name: "Louça suja"
    icon: mdi:alert-box

group:

  movimento_luz_status_lava_loucas:
    control: hidden
    view: false
    entities:
    - binary_sensor.movimento_sala
    - binary_sensor.movimento_cozinha
    - binary_sensor.movimento_entrada_de_casa
    name: Movimento status lava-louças
