input_select:
  
  rf_bridge_device_select:
    name: 'Dispositivo'
    initial: Selecionar
    options:
      - "Selecionar"
      - "Casa"
      - "MuvRH"

  rf_bridge_mode_select:
    name: 'Modo'
    initial: Selecionar
    options:
      - "Selecionar"
      - "Aprender"
      - "Enviar"

  rf_bridge_key_select:
    name: 'Key'
    initial: Selecionar
    options:
      - "Selecionar"
      - "01"
      - "02"
      - "03"
      - "04"
      - "05"
      - "06"
      - "07"
      - "08"
      - "09"
      - "10"
      - "11"
      - "12"
      - "13"
      - "14"
      - "15"
      - "16"

script:

  rf_bridge_send_command:
    alias: "Enviar comando"
    sequence:
    - service: mqtt.publish
      data_template:
        topic: "cmnd/{% if is_state('input_select.rf_bridge_device_select', 'Casa') %}rfbridgecasa{% elif is_state('input_select.rf_bridge_device_select', 'MuvRH') %}rfbridgemuvrh{% endif %}/backlog"
        payload: "rfkey{{ states('input_select.rf_bridge_key_select') }} {% if is_state('input_select.rf_bridge_mode_select', 'Aprender') %}2{% elif is_state('input_select.rf_bridge_mode_select', 'Enviar') %}1{% endif %}"
    - service: input_select.select_option
      entity_id: input_select.rf_bridge_device_select
      data_template:
        option: "Selecionar"
    - service: input_select.select_option
      entity_id: input_select.rf_bridge_mode_select
      data_template:
        option: "Selecionar"
    - service: input_select.select_option
      entity_id: input_select.rf_bridge_key_select
      data_template:
        option: "Selecionar"

  rf_chegar_em_casa:
    alias: "Automação chegar em casa - RF"
    sequence:
    - service: input_boolean.turn_on
      entity_id: input_boolean.chegar_casa

  rf_chegar_no_trabalho:
    alias: "Automação chegar no trabalho - RF"
    sequence:
    - service: input_boolean.turn_on
      entity_id: input_boolean.entrar_muvrh

  rf_sair_no_trabalho:
    alias: "Automação sair no trabalho - RF"
    sequence:
    - service: input_boolean.turn_on
      entity_id: input_boolean.sair_muvrh

  rf_chuveiro_suite_toggle:
    alias: "Ligar ou desligar chuveiro da súite - RF"
    sequence:
    - service: switch.toggle
      entity_id: switch.chuveirosuite

  rf_chuveiro_social_toggle:
    alias: "Ligar ou desligar chuveiro social - RF"
    sequence:
    - service: switch.toggle
      entity_id: switch.chuveirosocial

group:

  rf_bridge_controles:
    control: hidden
    entities:
    - input_select.rf_bridge_device_select
    - input_select.rf_bridge_mode_select
    - input_select.rf_bridge_key_select
    - script.rf_bridge_send_command
    name: Controles Rf Bridge
    view: false

homeassistant:
  customize:

    input_select.rf_bridge_device_select:
      icon: mdi:access-point
    
    input_select.rf_bridge_mode_select:
      icon: mdi:swap-vertical
    
    input_select.rf_bridge_key_select:
      icon: mdi:format-list-numbered
    
    script.rf_bridge_send_command:
      icon: mdi:send

automation:

  - alias: Automação - RF Bridge Casa
    initial_state: true
    trigger:
      platform: mqtt
      topic: tele/rfbridgecasa/RESULT
    condition:
      condition: template
      value_template: "{% if trigger.payload_json.RfReceived.RfKey == 'None' %}False{% else %}True{% endif %}"
    action:
      - service_template: >
          {% if trigger.payload_json.RfReceived.RfKey == 1 %}
            script.rf_chegar_em_casa
          {% elif trigger.payload_json.RfReceived.RfKey == 2 %}
            script.garagem_casa_abrir
          {% elif trigger.payload_json.RfReceived.RfKey == 3 %}
            script.rf_chegar_em_casa
          {% elif trigger.payload_json.RfReceived.RfKey == 4 %}
            script.rf_sair_no_trabalho
          {% elif trigger.payload_json.RfReceived.RfKey == 5 %}
            script.rf_chuveiro_suite_toggle
          {% elif trigger.payload_json.RfReceived.RfKey == 6 %}
            script.rf_chuveiro_social_toggle
          {% else %}
            script.nada
          {% endif %}

  - alias: Automação - RF Bridge MuvRH
    initial_state: true
    trigger:
      platform: mqtt
      topic: tele/rfbridgemuvrh/RESULT
    condition:
      condition: template
      value_template: "{% if trigger.payload_json.RfReceived.RfKey == 'None' %}False{% else %}True{% endif %}"
    action:
      - service_template: >
          {% if trigger.payload_json.RfReceived.RfKey == 1 %}
            script.rf_chegar_no_trabalho
          {% elif trigger.payload_json.RfReceived.RfKey == 2 %}
            script.rf_sair_no_trabalho
          {% else %}
            script.nada
          {% endif %}