automation:

  - alias: Rotina - Ações ao por do sol
    initial_state: true
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:15:00'
      - platform: sun
        event: sunset
        offset: '-00:50:00'
    condition:
      condition: template
      value_template: "{{ trigger.offset.total_seconds() == -15*60 or states('sensor.dark_sky_cloud_coverage')|int(0) > 80 }}"
    action:
      - service: homeassistant.turn_on
        entity_id:
          - automation.luzes_da_casa_banheiro_social
          - automation.luzes_da_casa_banheiro_suite
          - automation.luzes_da_casa_cozinha
          - automation.luzes_da_casa_quarto
          - automation.luzes_da_casa_suite
          - automation.luzes_da_casa_sala
          - automation.luzes_da_casa_entrando_em_casa
          - automation.muvrh_203_luz_do_banheiro
          - automation.muvrh_203_luz_da_sala_de_operacoes
          - automation.muvrh_203_luz_da_nossa_sala
          - automation.muvrh_303_luz_da_entrada
          - automation.muvrh_303_luz_da_dinamica
          - automation.muvrh_303_luz_do_banheiro

  - alias: Rotina - Ações ao nascer do sol
    initial_state: true
    trigger:
      - platform: sun
        event: sunrise
        offset: '00:15:00'
      - platform: sun
        event: sunrise
        offset: '00:50:00'
    condition:
      condition: template
      value_template: "{{ trigger.offset.total_seconds() == 15*60 or states('sensor.dark_sky_cloud_coverage')|int(0) > 80 }}"
    action:
      - service: homeassistant.turn_off
        entity_id:
          - automation.luzes_da_casa_banheiro_social
          - automation.luzes_da_casa_banheiro_suite
          - automation.luzes_da_casa_cozinha
          - automation.luzes_da_casa_quarto
          - automation.luzes_da_casa_suite
          - automation.luzes_da_casa_sala
          - automation.luzes_da_casa_entrando_em_casa
          - automation.muvrh_203_luz_do_banheiro
          - automation.muvrh_203_luz_da_sala_de_operacoes
          - automation.muvrh_203_luz_da_nossa_sala
          - automation.muvrh_303_luz_da_entrada
          - automation.muvrh_303_luz_da_dinamica
          - automation.muvrh_303_luz_do_banheiro
      - service: cover.close_cover
        entity_id: cover.persiana_sala

  - alias: Rotina - Bom dia
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.bom_dia
      to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.boa_noite
      - service: script.tts_bom_dia
      - service: persistent_notification.create
        data:
          title: "Alerta Casa ({{now().strftime('%H:%M')}})"
          message: "Bom dia!"
      - service: notify.todos_celulares
        data_template:
          title: "Automação"
          message: "Bom dia! Hoje a máxima será de {{ states.sensor.dark_sky_daytime_high_temperature_0.state | int }}ºC com previsão de {{ states.sensor.dark_sky_summary.state | lower }}"
      - service: switch.turn_on
        entity_id: switch.toalheiro
      - service_template: >-
          {% if is_state('input_boolean.cafe_manha', 'on') %}
            switch.turn_on
          {% else %}
            script.nada
          {% endif %}
        data_template:
          entity_id: >-
              {% if is_state('input_boolean.cafe_manha', 'on') %}
                switch.cafeteira_casa
              {% endif %}
      - service_template: >-
          {% if is_state('climate.ar_condicionado_da_suite' , 'off') %}
            script.nada
          {% else %}
            {% if is_state('climate.ar_condicionado_da_suite' , 'heat') %}
            {% else %}
              climate.set_operation_mode
            {% endif %}
          {% endif %}
        data:
          entity_id: climate.ar_condicionado_da_suite
          operation_mode: 'off'
      - wait_template: "{{is_state('script.tts_bom_dia', 'off')}}"
      - service: switch.turn_on
        entity_id: switch.tv_lg_suite
      - delay: '00:05:00'
      - service: input_boolean.turn_off
        entity_id: input_boolean.bom_dia

  - alias: Rotina - Boa noite
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.boa_noite
      to: 'on'
    action:
      - service: notify.todos_celulares
        data:
          title: "Automação"
          message: "Aprontando a casa. Boa noite!"
      - service: persistent_notification.create
        data:
          title: "Alerta Casa ({{now().strftime('%H:%M')}})"
          message: "Boa noite!"
      - service: homeassistant.turn_off
        entity_id:
          - automation.luzes_da_casa_suite
          - automation.luzes_da_casa_quarto
      - service: script.casa_desligar_tudo_noite
      - service: script.tts_boa_noite

  - alias: Google Home audio - Ajustar volume no banho
    initial_state: true
    trigger:
      platform: state
      entity_id:
        - switch.chuveirosuite
        - switch.chuveirosocial
      from: 'off'
      to: 'on'
    condition:
      condition: template
      value_template: "{{ ( trigger.to_state.entity_id == 'switch.chuveirosuite' and is_state('media_player.banheiro_da_suite' , 'playing') ) or ( trigger.to_state.entity_id == 'switch.chuveirosocial' and is_state('media_player.banheiro_social' , 'playing') ) }}"
    action:
      - delay: '00:00:02'
      - service: media_player.volume_set
        data_template:
          volume_level: 0.8
          entity_id: "{{ 'media_player.banheiro_da_suite' if trigger.to_state.entity_id == 'switch.chuveirosuite' else 'media_player.banheiro_social' }}"
      - wait_template: >-
          {% if trigger.to_state.entity_id == 'switch.chuveirosuite' %}
            {{ is_state('switch.chuveirosuite' , 'off') }}
          {% else %}
            {{ is_state('switch.chuveirosocial' , 'off') }}
          {% endif %}
      - delay: '00:00:02'
      - service: media_player.volume_set
        data_template:
          volume_level: 0.4
          entity_id: "{{ 'media_player.banheiro_da_suite' if trigger.to_state.entity_id == 'switch.chuveirosuite' else 'media_player.banheiro_social' }}"

script:

## Desligar tudo boa noite

  casa_desligar_tudo_noite:
    alias: "Desligar tudo em casa - boa noite"
    sequence:
      - service: script.casa_desligar_tudo_media_players
      - service: cover.close_cover
        entity_id: cover.persiana_suite
      - delay: '00:00:02'
      - service_template: >-
          {% if not is_state('climate.ar_condicionado_da_suite' , 'off') %}
            script.ar_suite_display
          {% else %}
            script.nada
          {% endif %}
      - service: script.casa_desligar_ar_sala
      - service_template: >-
          {% set lights = ['light.area_servico','light.suite_banheiro_principal','light.suite_banheiro_espelho','light.corredor','light.cozinha','light.entrada','light.ledchaocozinha','light.ledcozinhabalcao','light.ledsaladesktop','light.ledsalatv','light.ledsuitecama','light.ledsuitetv','light.mesa_de_jantar','light.sala_principal','light.suite_principal','light.status_maquina_de_lavar_loucas','light.movel_da_sala'] %}
          {% for item in lights if states(item) == 'on' %}
          {% if loop.first %}
            light.turn_off
          {% endif %}
          {% else %}
            script.nada
          {% endfor %}
        data_template:
          entity_id: >-
            {% set entities = ['light.area_servico','light.suite_banheiro_principal','light.suite_banheiro_espelho','light.corredor','light.cozinha','light.entrada','light.ledchaocozinha','light.ledcozinhabalcao','light.ledsaladesktop','light.ledsalatv','light.ledsuitecama','light.ledsuitetv','light.mesa_de_jantar','light.sala_principal','light.suite_principal','light.status_maquina_de_lavar_loucas','light.movel_da_sala'] %}
            {{ states.light | selectattr('entity_id', 'in', entities) | selectattr('state','eq','on') | map(attribute='entity_id') | join(', ') }}
      - delay: '00:00:02'
      - service_template: >-
          {% set switches = ['switch.chuveirosuite','switch.toalheiro','switch.tv_lg_sala','switch.tv_lg_suite','switch.muvrh_cafeteira','switch.cafeteira_casa','switch.chaleira_casa','switch.ventilador_casa','switch.home_theater_sala'] %}
          {% for item in switches if states(item) == 'on' %}
          {% if loop.first %}
            switch.turn_off
          {% endif %}
          {% else %}
            script.nada
          {% endfor %}
        data_template:
          entity_id: >-
              {% set entities = ['switch.chuveirosuite','switch.toalheiro','switch.tv_lg_sala','switch.tv_lg_suite','switch.muvrh_cafeteira','switch.cafeteira_casa','switch.chaleira_casa','switch.ventilador_casa','switch.home_theater_sala'] %}
              {{ states.switch| selectattr('entity_id', 'in', entities) | selectattr('state','eq','on') | map(attribute='entity_id') | join(', ') }}
      - condition: state
        entity_id: input_boolean.visita_casa
        state: 'off'
      - service: script.casa_desligar_ar_quarto
      - delay: '00:00:02'
      - service_template: >-
          {% set lights = ['light.quarto','light.ledquartotv','light.banheiro_social_principal','light.banheiro_social_espelho'] %}
          {% for item in lights if states(item) == 'on' %}
          {% if loop.first %}
            light.turn_off
          {% endif %}
          {% else %}
            script.nada
          {% endfor %}
        data_template:
          entity_id: >-
              {% set entities = ['light.quarto','light.ledquartotv','light.banheiro_social_principal','light.banheiro_social_espelho'] %}
              {{ states.light | selectattr('entity_id', 'in', entities) | selectattr('state','eq','on') | map(attribute='entity_id') | join(', ') }}
      - service_template: >-
          {% set switches = ['switch.chuveirosocial','switch.tv_lg_quarto'] %}
          {% for item in switches if states(item) == 'on' %}
          {% if loop.first %}
            switch.turn_off
          {% endif %}
          {% else %}
            script.nada
          {% endfor %}
        data_template:
          entity_id: >-
              {% set entities = ['switch.chuveirosocial','switch.tv_lg_quarto'] %}
              {{ states.switch| selectattr('entity_id', 'in', entities) | selectattr('state','eq','on') | map(attribute='entity_id') | join(', ') }}

## Desligar tudo em casa

  casa_desligar_tudo:
    alias: "Desligar tudo em casa"
    sequence:
      - service: script.casa_desligar_tudo_climates
      - service: script.casa_desligar_tudo_lights
      - service: script.casa_desligar_tudo_switches
      - service: script.casa_desligar_tudo_media_players
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.alarme

  casa_desligar_tudo_climates:
    alias: "Desligar todas os ares condicionados"
    sequence:
      - condition: template
        value_template: "{{ not is_state('climate.ar_condicionado_da_suite' , 'off') or not is_state('climate.ar_condicionado_do_quarto' , 'off') or not is_state('climate.ar_condicionado_da_sala' , 'off') }}"
      - service: climate.set_operation_mode
        data_template:
          operation_mode: 'off'
          entity_id: >-
              {% set entities = ['climate.ar_condicionado_da_suite','climate.ar_condicionado_do_quarto','climate.ar_condicionado_da_sala'] %}
              {{ states.climate | selectattr('entity_id', 'in', entities) | selectattr('state','!=','off') | map(attribute='entity_id') | join(', ') }}

  casa_desligar_tudo_lights:
    alias: "Desligar todas as luzes"
    sequence:
      - condition: template
        value_template: >-
          {% set lights = ['light.area_servico','light.suite_banheiro_principal','light.suite_banheiro_espelho','light.corredor','light.cozinha','light.entrada','light.ledchaocozinha','light.ledcozinhabalcao','light.ledquartotv','light.ledsaladesktop','light.ledsalatv','light.ledsuitecama','light.ledsuitetv','light.mesa_de_jantar','light.quarto','light.sala_principal','light.banheiro_social_principal','light.banheiro_social_espelho','light.suite_principal','light.status_maquina_de_lavar_loucas','light.movel_da_sala','light.coifa_luz'] %}
          {% for item in lights if states(item) == 'on' %}
          {% if loop.first %}
            {{ true }}
          {% endif %}
          {% else %}
            False
          {% endfor %}
      - service: light.turn_off
        data_template:
          entity_id: >-
              {% set lights = ['light.area_servico','light.suite_banheiro_principal','light.suite_banheiro_espelho','light.corredor','light.cozinha','light.entrada','light.ledchaocozinha','light.ledcozinhabalcao','light.ledquartotv','light.ledsaladesktop','light.ledsalatv','light.ledsuitecama','light.ledsuitetv','light.mesa_de_jantar','light.quarto','light.sala_principal','light.banheiro_social_principal','light.banheiro_social_espelho','light.suite_principal','light.status_maquina_de_lavar_loucas','light.movel_da_sala','light.coifa_luz'] %}
              {{ states.light | selectattr('entity_id', 'in', lights) | selectattr('state','eq','on') | map(attribute='entity_id') | join(', ') }}

  casa_desligar_tudo_switches:
    alias: "Desligar todas os dispositivos"
    sequence:
      - condition: template
        value_template: >-
          {% set switches = ['switch.chuveirosuite','switch.toalheiro','switch.tv_lg_sala','switch.tv_lg_suite','switch.chuveirosocial','switch.tv_lg_quarto','switch.cafeteira_casa','switch.chaleira_casa','switch.ventilador_casa','switch.home_theater_sala','switch.coifa_motor'] %}
          {% for item in switches if states(item) == 'on' %}
          {% if loop.first %}
            {{ true }}
          {% endif %}
          {% else %}
            False
          {% endfor %}
      - service: switch.turn_off
        data_template:
          entity_id: >-
              {% set switches = ['switch.chuveirosuite','switch.toalheiro','switch.tv_lg_sala','switch.tv_lg_suite','switch.chuveirosocial','switch.tv_lg_quarto','switch.cafeteira_casa','switch.chaleira_casa','switch.ventilador_casa','switch.home_theater_sala','switch.coifa_motor'] %}
              {{ states.switch| selectattr('entity_id', 'in', switches) | selectattr('state','eq','on') | map(attribute='entity_id') | join(', ') }}

  casa_desligar_tudo_media_players:
    alias: "Desligar todas os media players"
    sequence:
      - condition: template
        value_template: >-
          {% set players = ['media_player.banheiro_social', 'media_player.banheiro_da_suite', 'media_player.cozinha', 'media_player.quarto', 'media_player.sala', 'media_player.suite'] %}
          {% for item in players if states(item) == 'playing' %}
          {% if loop.first %}
            {{ true }}
          {% endif %}
          {% else %}
            False
          {% endfor %}
      - service: media_player.turn_off
        data_template:
          entity_id: >-
              {% set players = ['media_player.banheiro_social', 'media_player.banheiro_da_suite', 'media_player.cozinha', 'media_player.quarto', 'media_player.sala', 'media_player.suite'] %}
              {{ states.media_player| selectattr('entity_id', 'in', players) | selectattr('state','eq','playing') | map(attribute='entity_id') | join(', ') }}

  casa_desligar_ar_sala:
    alias: "Desligar ar da sala"
    sequence:
      - condition: template
        value_template: "{{ not is_state('climate.ar_condicionado_da_sala' , 'off') }}"
      - service: climate.set_operation_mode
        data:
          operation_mode: 'off'
          entity_id: climate.ar_condicionado_da_sala

  casa_desligar_ar_suite:
    alias: "Desligar ar da suite"
    sequence:
      - condition: template
        value_template: "{{ not is_state('climate.ar_condicionado_da_suite' , 'off') }}"
      - service: climate.set_operation_mode
        data:
          operation_mode: 'off'
          entity_id: climate.ar_condicionado_da_suite

  casa_desligar_ar_quarto:
    alias: "Desligar ar da quarto"
    sequence:
      - condition: template
        value_template: "{{ not is_state('climate.ar_condicionado_do_quarto' , 'off') }}"
      - service: climate.set_operation_mode
        data:
          operation_mode: 'off'
          entity_id: climate.ar_condicionado_do_quarto

  bom_dia_sem_tts:
    alias: "Bom dia sem TTS"
    sequence:
      - service: input_boolean.turn_off
        entity_id: input_boolean.boa_noite
      - service: automation.turn_off
        entity_id: automation.rotina_bom_dia
      - service: input_boolean.turn_on
        entity_id: input_boolean.bom_dia
      - service: automation.turn_on
        entity_id: automation.rotina_bom_dia
      - service: persistent_notification.create
        data:
          title: "Alerta Casa ({{now().strftime('%H:%M')}})"
          message: "Bom dia!"
      - service: notify.todos_celulares
        data_template:
          title: "Automação"
          message: "Bom dia! Hoje a máxima será de {{ states.sensor.dark_sky_daytime_high_temperature_0.state | int }}ºC com previsão de {{ states.sensor.dark_sky_summary.state | lower }}"
      - service: switch.turn_on
        entity_id: switch.toalheiro
      - service_template: >-
          {% if is_state('input_boolean.cafe_manha', 'on') %}
            switch.turn_on
          {% else %}
            script.nada
          {% endif %}
        data_template:
          entity_id: >-
              {% if is_state('input_boolean.cafe_manha', 'on') %}
                switch.cafeteira_casa
              {% endif %}
      - service_template: >-
          {% if is_state('input_boolean.chaleira_manha', 'on') %}
            switch.turn_on
          {% else %}
            script.nada
          {% endif %}
        data_template:
          entity_id: >-
              {% if is_state('input_boolean.chaleira_manha', 'on') %}
                switch.chaleira_casa
              {% endif %}
      - service_template: >-
          {% if is_state('climate.ar_condicionado_da_suite' , 'off') %}
            script.nada
          {% else %}
            {% if is_state('climate.ar_condicionado_da_suite' , 'heat') %}
              script.nada
            {% else %}
              climate.set_operation_mode
            {% endif %}
          {% endif %}
        data:
          entity_id: climate.ar_condicionado_da_suite
          operation_mode: 'off'
      - delay: '00:05:00'
      - service: input_boolean.turn_off
        entity_id: input_boolean.bom_dia

  boa_noite_sem_tts:
    alias: "Bom dia sem TTS"
    sequence:
      - service: automation.turn_off
        entity_id: automation.rotina_boa_noite
      - service: input_boolean.turn_on
        entity_id: input_boolean.boa_noite
      - service: automation.turn_on
        entity_id: automation.rotina_boa_noite
      - service: notify.todos_celulares
        data:
          title: "Automação"
          message: "Aprontando a casa. Boa noite!"
      - service: persistent_notification.create
        data:
          title: "Alerta Casa ({{now().strftime('%H:%M')}})"
          message: "Boa noite!"
      - service: homeassistant.turn_off
        entity_id:
          - automation.luzes_da_casa_suite
          - automation.luzes_da_casa_quarto
      - service: script.casa_desligar_tudo_noite
      - delay: '00:00:10'
      - service: script.boa_noite_desligar_som_ghm

  boa_noite_desligar_som_ghm:
    alias: "Desligar som para dormir"
    sequence:
      - delay: '00:30:00'
      - service: media_player.turn_off
        entity_id: media_player.suite