- platform: template
  sensors:
    antonio:
      value_template: "{{ is_state('device_tracker.antonio' , 'home') or is_state('device_tracker.iphone_de_antonio' , 'home') or is_state('device_tracker.iphone_de_antonio' , 'Trabalho') }}"
      entity_id:
        - device_tracker.antonio
        - device_tracker.iphone_de_antonio
      friendly_name: 'Antonio'
      device_class: presence
      entity_picture_template: http://www.muvrh.com.br/images/colaboradores/antonio_schneider.png

    roberta:
      value_template: "{{ is_state('device_tracker.roberta' , 'home') or is_state('device_tracker.iphone_de_roberta' , 'home') or is_state('device_tracker.iphone_de_roberta' , 'Trabalho') }}"
      entity_id:
        - device_tracker.roberta
        - device_tracker.iphone_de_roberta
      friendly_name: 'Roberta'
      device_class: presence
      entity_picture_template: http://www.muvrh.com.br/images/colaboradores/roberta_fonseca.png

    casa_movimento:
      value_template: "{{ is_state('group.casa_movimento' , 'on') }}"
      entity_id: group.casa_movimento
      friendly_name: 'Movimento casa'
      device_class: occupancy

    energia_casa:
      value_template: "{{ is_state('group.energia_casa' , 'on') }}"
      entity_id: group.energia_casa
      friendly_name: 'Energia casa'
      device_class: power

    ar_suite:
      value_template: "{{ not is_state('climate.ar_condicionado_da_suite', 'off') }}"
      entity_id: climate.ar_condicionado_da_suite
      friendly_name: 'Ar condicionado da suíte'
      device_class: power

    ar_sala:
      value_template: "{{ not is_state('climate.ar_condicionado_da_sala', 'off') }}"
      entity_id: climate.ar_condicionado_da_sala
      friendly_name: 'Ar condicionado da sala'
      device_class: power

    ar_quarto:
      value_template: "{{ not is_state('climate.ar_condicionado_do_quarto', 'off') }}"
      entity_id: climate.ar_condicionado_do_quarto
      friendly_name: 'Ar condicionado da quarto'
      device_class: power

    muvrh_movimento_203:
      value_template: "{{ is_state('group.muvrh_movimento_203' , 'on') }}"
      entity_id: group.muvrh_movimento_203
      friendly_name: 'Movimento sala 203'
      device_class: occupancy

    muvrh_movimento_303:
      value_template: "{{ is_state('group.muvrh_movimento_303' , 'on') }}"
      entity_id: group.muvrh_movimento_303
      friendly_name: 'Movimento sala 303'
      device_class: occupancy

    muvrh_movimento:
      value_template: "{{ is_state('group.muvrh_movimento_203' , 'on') or is_state('group.muvrh_movimento_303' , 'on') }}"
      entity_id:
        - group.muvrh_movimento_203
        - group.muvrh_movimento_303
      friendly_name: 'Movimento MuvRH'
      device_class: occupancy

    casa_alerta_box_areia_magno:
      value_template: "{{ is_state('binary_sensor.box_banheiro_social' , 'off') and is_state('input_boolean.magno_em_casa' , 'on') }}"
      entity_id:
        - binary_sensor.box_banheiro_social
        - input_boolean.magno_em_casa
      friendly_name: 'Box da areia fechado'
      device_class: problem

- platform: mqtt
  name: "Estado TV sala dinâmica"
  state_topic: "tele/muv303tvdinamica/LWT"
  value_template: "{{ value }}"
  payload_on: "Online"
  payload_off: "Offline"
  device_class: power

- platform: mqtt
  name: "Movimento entrada de casa"
  state_topic: "wallpanel/tablet_entrada_casa/sensor/motion"
  payload_on: '{"value":true}'
  payload_off: '{"value":false}'
  device_class: motion 

#- platform: mqtt
#  name: "Estado TV sala operações"
#  state_topic: "devices/muv203tvoperacoes/LWT"
#  value_template: "{{ value }}"
#  payload_on: "ONLINE"
#  payload_off: "OFFLINE"
#  device_class: power

- platform: octoprint
  monitored_conditions:
    - Printing
    - Printing Error
