- platform: mjpeg
  name: "Ender 3"
  mjpeg_url: http://192.168.1.69/webcam/?action=stream
  still_image_url: http://192.168.1.69:8080/?action=snapshot

#SriCcam

#- platform: ffmpeg
#  name: "MuvRH 203 - Operações"
#  input: -rtsp_transport tcp -i rtsp://192.168.1.54:554/onvif1

## Wyze

- platform: ffmpeg
  name: "MuvRH 203 - Operações"
  input: !secret url_wyze_203_operacoes

- platform: ffmpeg
  name: "MuvRH 303 - Dinâmica"
  input: !secret url_wyze_303_dinamica

- platform: ffmpeg
  name: "Casa - Sala"
  input: !secret url_wyze_casa_sala