- platform: mjpeg
  name: "Ender 3"
  mjpeg_url: http://192.168.1.69/webcam/?action=stream
  still_image_url: http://192.168.1.69:8080/?action=snapshot

- platform: ffmpeg
  name: "MuvRH 303 - Dinâmica"
  input: !secret url_wyze_303_dinamica

- platform: ffmpeg
  name: "MuvRH 203 - Operações"
  input: rtsp://192.168.1.54:554/onvif1
