# Casa

- platform: smartir
  name: Ar condicionado da suite
  device_code: 1380
  controller_send_service: switch.broadlink_send_packet_192_168_1_32
  temperature_sensor: sensor.temperatura_suite
  humidity_sensor: sensor.umidade_suite

- platform: smartir
  name: Ar condicionado da sala
  device_code: 1380
  controller_send_service: switch.broadlink_send_packet_192_168_1_34
  temperature_sensor: sensor.temperatura_sala
  humidity_sensor: sensor.umidade_sala

- platform: smartir
  name: Ar condicionado do quarto
  device_code: 1380
  controller_send_service: switch.broadlink_send_packet_192_168_1_33
  temperature_sensor: sensor.temperatura_quarto
  humidity_sensor: sensor.umidade_quarto

# MuvRH

- platform: smartir
  name: Ar condicionado da nossa sala
  device_code: 1240
  controller_send_service: switch.broadlink_send_packet_192_168_1_35
  temperature_sensor: sensor.temperatura_real_nossa_sala

- platform: smartir
  name: Ar condicionado da sala de operações
  device_code: 1380
  controller_send_service: switch.broadlink_send_packet_192_168_1_36
  temperature_sensor: sensor.temperature_158d00015633b4
  humidity_sensor: sensor.humidity_158d00015633b4

- platform: smartir
  name: Ar condicionado da entrada 203
  device_code: 1380
  controller_send_service: switch.broadlink_send_packet_192_168_1_37
  temperature_sensor: sensor.temperature_158d0001d7e65d
  humidity_sensor: sensor.humidity_158d0001d7e65d

- platform: smartir
  name: Ar condicionado da sala 303
  device_code: 1380
  controller_send_service: switch.broadlink_send_packet_192_168_1_41
  temperature_sensor: sensor.temperature_158d0001703b44
  humidity_sensor: sensor.humidity_158d0001703b44