#Casa

- platform: broadlink
  name: Ar condicionado da suite
  host: 192.168.1.32
  mac: 'B4:43:0D:EE:F4:76'
  ircodes_ini: 'broadlink_climate_codes/midea.ini'
  min_temp: 18
  max_temp: 30
  target_temp: 24
  temp_sensor: sensor.temperature_158d0001dcb597
  default_operation: idle
  default_fan_mode: low
  customize:
    operations:
      - idle
      - cool
      - heat
      - auto
    fan_modes:
      - low
      - mid
      - high

- platform: broadlink
  name: Ar condicionado da sala
  host: 192.168.1.34
  mac: 'B4:43:0D:F0:A1:A1'
  ircodes_ini: 'broadlink_climate_codes/midea.ini'
  min_temp: 18
  max_temp: 30
  target_temp: 24
  temp_sensor: sensor.temperature_158d0001700b20
  default_operation: idle
  default_fan_mode: mid
  customize:
    operations:
      - idle
      - cool
      - heat
      - auto
    fan_modes:
      - low
      - mid
      - high

- platform: broadlink
  name: Ar condicionado do quarto
  host: 192.168.1.33
  mac: 'B4:43:0D:F9:2E:6F'
  ircodes_ini: 'broadlink_climate_codes/midea.ini'
  min_temp: 18
  max_temp: 30
  target_temp: 24
  temp_sensor: sensor.temperature_158d0001702175
  default_operation: idle
  default_fan_mode: low
  customize:
    operations:
      - idle
      - cool
      - heat
      - auto
    fan_modes:
      - low
      - mid
      - high

#MuvRH

- platform: broadlink
  name: Ar condicionado da nossa sala
  host: 192.168.1.35
  mac: '34:EA:34:E4:5F:2F'
  ircodes_ini: 'broadlink_climate_codes/consul.ini'
  min_temp: 18
  max_temp: 30
  target_temp: 22
  temp_sensor: sensor.temperatura_real_nossa_sala
  default_operation: idle
  default_fan_mode: low
  customize:
    operations:
      - idle
      - cool
      - heat
      - auto
    fan_modes:
      - low
      - mid
      - high

- platform: broadlink
  name: Ar condicionado da sala de operações
  host: 192.168.1.36
  mac: '34:EA:34:E3:B6:31'
  ircodes_ini: 'broadlink_climate_codes/midea.ini'
  min_temp: 18
  max_temp: 30
  target_temp: 24
  temp_sensor: sensor.temperature_158d00015633b4
  default_operation: idle
  default_fan_mode: low
  customize:
    operations:
      - idle
      - cool
      - heat
      - auto
    fan_modes:
      - low
      - mid
      - high

- platform: broadlink
  name: Ar condicionado da entrada 203
  host: 192.168.1.37
  mac: '34:EA:34:8F:0C:C8'
  ircodes_ini: 'broadlink_climate_codes/midea.ini'
  min_temp: 18
  max_temp: 30
  target_temp: 24
  temp_sensor: sensor.temperature_158d0001d7e65d
  default_operation: idle
  default_fan_mode: low
  customize:
    operations:
      - idle
      - cool
      - heat
      - auto
    fan_modes:
      - low
      - mid
      - high

- platform: broadlink
  name: Ar condicionado da sala 303
  host: 192.168.1.41
  mac: '34:EA:34:8F:0B:01'
  ircodes_ini: 'broadlink_climate_codes/midea.ini'
  min_temp: 18
  max_temp: 30
  target_temp: 24
  temp_sensor: sensor.temperature_158d0001703b44
  default_operation: idle
  default_fan_mode: low
  customize:
    operations:
      - idle
      - cool
      - heat
      - auto
    fan_modes:
      - low
      - mid
      - high