- platform: template
  covers:
    persiana_suite:
      optimistic: true
      set_cover_position:
        service_template: >
          {% if states.cover.persiana_suite.attributes.current_position >= 51 %}
            script.persiana_suite_fechar
          {% elif states.cover.persiana_suite.attributes.current_position <= 50 %}
            script.persiana_suite_abrir
          {% endif %}
      open_cover:
        service: script.persiana_suite_abrir
      close_cover:
        service: script.persiana_suite_fechar
      stop_cover:
        service: script.persiana_suite_parar
      friendly_name: "Persiana da suíte"
    persiana_quarto:
      optimistic: true
      set_cover_position:
        service_template: >
          {% if states.cover.persiana_quarto.attributes.current_position >= 51 %}
            script.persiana_quarto_fechar
          {% elif states.cover.persiana_quarto.attributes.current_position <= 50 %}
            script.persiana_quarto_abrir
          {% endif %}
      open_cover:
        service: script.persiana_quarto_abrir
      close_cover:
        service: script.persiana_quarto_fechar
      stop_cover:
        service: script.persiana_quarto_parar
      friendly_name: "Persiana do quarto"
    persiana_sala:
      optimistic: true
      set_cover_position:
        service_template: >
          {% if states.cover.persiana_sala.attributes.current_position >= 51 %}
            script.persiana_sala_fechar
          {% elif states.cover.persiana_sala.attributes.current_position <= 50 %}
            script.persiana_sala_abrir
          {% endif %}
      open_cover:
        service: script.persiana_sala_abrir
      close_cover:
        service: script.persiana_sala_fechar
      stop_cover:
        service: script.persiana_sala_parar
      friendly_name: "Persiana da sala"

#Garagens

    garagem_casa:
      open_cover:
        service: script.garagem_casa_abrir
      close_cover:
        service: script.garagem_casa_fechar
      friendly_name: "Garagem de casa"
    garagem_muvrh_rua:
      open_cover:
        service: script.garagem_muvrh_rua_abrir
      close_cover:
        service: script.garagem_muvrh_rua_fechar
      friendly_name: "Garagem da rua do trabalho"
    garagem_muvrh_interno:
      open_cover:
        service: script.garagem_muvrh_interno_abrir
      close_cover:
        service: script.garagem_muvrh_interno_fechar
      friendly_name: "Garagem de dentro do trabalho"