- platform: nmap_tracker
  interval_seconds: 30
  consider_home: 300
  track_new_devices: false
  scan_options: " -sP --host-timeout 10s"
  hosts: 192.168.1.10-110
  home_interval: 5
  exclude:
     - 192.168.1.12
  
#- platform: tplink
#  host: 192.168.1.1
#  username: !secret TP_Link_Admin
#  password: !secret TP_Link_password