#Casa

#Grupos de luzes

- platform: group
  name: "Luzes principais sala"
  entities:
    - light.ledsalatv
    - light.ledsaladesktop

- platform: group
  name: "Luzes principais cozinha"
  entities:
    - light.cozinha
    - light.ledcozinhabalcao
    - light.ledchaocozinha

- platform: group
  name: "Todos os leds cozinha"
  entities:
    - light.ledcozinhabalcao
    - light.ledchaocozinha

- platform: group
  name: "Todas as luzes cozinha"
  entities:
    - light.cozinha
    - light.ledcozinhabalcao
    - light.ledchaocozinha
    - light.area_servico

- platform: group
  name: "Luzes principais quarto"
  entities:
    - light.ledquartotv
    - light.quarto

- platform: group
  name: "Todas as luzes suíte"
  entities:
    - light.suite_principal
    - light.ledsuitetv
    - light.ledsuitecama

- platform: group
  name: "Todos os leds suíte"
  entities:
    - light.ledsuitetv
    - light.ledsuitecama

- platform: group
  name: "Tudo banheiro suíte"
  entities:
    - light.suite_banheiro_principal
    - light.suite_banheiro_espelho

- platform: group
  name: "Tudo banheiro social"
  entities:
    - light.banheiro_social_principal
    - light.banheiro_social_espelho

- platform: group
  name: "Ender 3"
  entities:
    - light.ledsaladesktop
    - light.mesa_de_jantar
    - light.entrada
    - light.sala_principal

- platform: template
  lights:
    neopixel_movel_sala:
      friendly_name: "Neopixel móvel da sala"
      value_template: "{{ states.light.movel_da_sala.state }}"
      turn_on:
        service: light.turn_on
        data:
          entity_id: light.movel_da_sala
          transition: 3
          rgb_color: [255,0,0]
          brightness_pct: 100
          effect: 'Rainbow'
      turn_off:
        service: light.turn_off
        data:
          entity_id: light.movel_da_sala
