#Casa

#Grupos de luzes

- platform: group
  name: "Luzes principais sala"
  entities:
    - light.ledsalatv
    - light.ledsaladesktop

- platform: group
  name: "Luzes principais cozinha"
  entities:
    - light.cozinha
    - light.ledcozinhabalcao
    - light.ledchaocozinha

- platform: group
  name: "Todos os leds cozinha"
  entities:
    - light.ledcozinhabalcao
    - light.ledchaocozinha

- platform: group
  name: "Todas as luzes cozinha"
  entities:
    - light.cozinha
    - light.ledcozinhabalcao
    - light.ledchaocozinha
    - light.area_servico

- platform: group
  name: "Luzes principais quarto"
  entities:
    - light.ledquartotv
    - light.quarto

- platform: group
  name: "Todas as luzes suíte"
  entities:
    - light.suite_principal
    - light.ledsuitetv
    - light.ledsuitecama

- platform: group
  name: "Todos os leds suíte"
  entities:
    - light.ledsuitetv
    - light.ledsuitecama

- platform: group
  name: "Tudo banheiro suíte"
  entities:
    - light.suite_banheiro_principal
    - light.suite_banheiro_espelho

- platform: group
  name: "Tudo banheiro social"
  entities:
    - light.banheiro_social_principal
    - light.banheiro_social_espelho

- platform: group
  name: "Ender 3"
  entities:
    - light.ledsaladesktop
    - light.mesa_de_jantar
    - light.entrada
    - light.sala_principal