#Casa

#Grupos de luzes

- platform: group
  name: "Luzes principais sala"
  entities:
    - light.ledsalatv
    - light.ledsaladesktop

- platform: group
  name: "Luzes principais cozinha"
  entities:
    - light.cozinha
    - light.ledcozinhabalcao
    - light.ledchaocozinha

- platform: group
  name: "Todos os leds cozinha"
  entities:
    - light.ledcozinhabalcao
    - light.ledchaocozinha
    - light.coifa_luz

- platform: group
  name: "Todas as luzes cozinha"
  entities:
    - light.cozinha
    - light.ledcozinhabalcao
    - light.ledchaocozinha
    - light.area_servico
    - light.coifa_luz

- platform: group
  name: "Luzes principais quarto"
  entities:
    - light.ledquartotv_effects
    - light.quarto

- platform: group
  name: "Todas as luzes suíte"
  entities:
    - light.suite_principal
    - light.ledsuitetv
    - light.ledsuitecama

- platform: group
  name: "Todos os leds suíte"
  entities:
    - light.ledsuitetv
    - light.ledsuitecama

- platform: group
  name: "Tudo banheiro suíte"
  entities:
    - light.suite_banheiro_principal
    - light.suite_banheiro_espelho

- platform: group
  name: "Tudo banheiro social"
  entities:
    - light.banheiro_social_principal
    - light.banheiro_social_espelho

- platform: group
  name: "Ender 3"
  entities:
    - light.ledsaladesktop
    - light.mesa_de_jantar
    - light.entrada
    - light.sala_principal

- platform: template
  lights:
    neopixel_movel_sala:
      friendly_name: "Arco-íris"
      value_template: "{{ is_state('light.movel_da_sala', 'on') }}"
      entity_id: light.movel_da_sala
      turn_on:
        service: light.turn_on
        data:
          entity_id: light.movel_da_sala
          transition: 3
          rgb_color: [255,0,0]
          brightness_pct: 100
          effect: 'Rainbow'
      turn_off:
        service: light.turn_off
        data:
          entity_id: light.movel_da_sala

    ledsalatv_effects:
      friendly_name: "LED da TV da sala com efeitos"
      value_template: "{{ is_state('light.ledsalatv', 'on') }}"
      entity_id: light.ledsalatv
      turn_on:
        service: light.turn_on
        data:
          entity_id: light.ledsalatv
          transition: 3
          rgb_color: [255,0,0]
          brightness_pct: 100
          effect: 'RGB transition slow'
      turn_off:
        service: light.turn_off
        data:
          entity_id: light.ledsalatv

    ledquartotv_effects:
      friendly_name: "LED da TV do quarto com efeitos"
      value_template: "{{ is_state('light.ledquartotv', 'on') }}"
      entity_id: light.ledquartotv
      turn_on:
        service: light.turn_on
        data:
          entity_id: light.ledquartotv
          transition: 3
          rgb_color: [255,0,0]
          brightness_pct: 100
          effect: 'RGB transition fast'
      turn_off:
        service: light.turn_off
        data:
          entity_id: light.ledquartotv
