#Casa

- platform: mqtt
  name: "mesa_jantar"
  command_topic: "cmnd/mesajantar/POWER"
  state_topic: "stat/mesajantar/POWER"
  availability_topic: "tele/mesajantar/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "sala_principal"
  command_topic: "cmnd/salaprincipal/POWER"
  state_topic: "stat/salaprincipal/POWER"
  availability_topic: "tele/salaprincipal/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "suite_principal"
  command_topic: "cmnd/suiteprincipal/POWER"
  state_topic: "stat/suiteprincipal/POWER"
  availability_topic: "tele/suiteprincipal/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "suite_banheiro_principal"
  command_topic: "cmnd/banheirosuite/POWER3"
  state_topic: "stat/banheirosuite/POWER3"
  availability_topic: "tele/banheirosuite/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "suite_banheiro_espelho"
  command_topic: "cmnd/banheirosuite/POWER4"
  state_topic: "stat/banheirosuite/POWER4"
  availability_topic: "tele/banheirosuite/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "corredor"
  command_topic: "cmnd/corredor/POWER"
  state_topic: "stat/corredor/POWER"
  availability_topic: "tele/corredor/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "banheiro_social_principal"
  command_topic: "cmnd/banheirosocial/POWER2"
  state_topic: "stat/banheirosocial/POWER2"
  availability_topic: "tele/banheirosocial/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "banheiro_social_espelho"
  command_topic: "cmnd/banheirosocial/POWER1"
  state_topic: "stat/banheirosocial/POWER1"
  availability_topic: "tele/banheirosocial/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "quarto"
  command_topic: "cmnd/quarto/POWER"
  state_topic: "stat/quarto/POWER"
  availability_topic: "tele/quarto/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "entrada"
  command_topic: "cmnd/entrada/POWER"
  state_topic: "stat/entrada/POWER"
  availability_topic: "tele/entrada/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "cozinha"
  command_topic: "cmnd/cozinha/POWER"
  state_topic: "stat/cozinha/POWER"
  availability_topic: "tele/cozinha/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "area_servico"
  command_topic: "cmnd/areadeservico/POWER"
  state_topic: "stat/areadeservico/POWER"
  availability_topic: "tele/areadeservico/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "ledsuitecama"
  effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
  state_topic: "stat/ledsuitecama/POWER"
  command_topic: "cmnd/ledsuitecama/POWER"
  brightness_state_topic: "cmnd/ledsuitecama/Dimmer"
  brightness_command_topic: "cmnd/ledsuitecama/Dimmer"
  brightness_scale: 100
  rgb_state_topic: "cmnd/ledsuitecama/Color"
  rgb_command_topic: "cmnd/ledsuitecama/Color"
  effect_command_topic: "cmnd/ledsuitecama/Scheme"
  effect_state_topic: "cmnd/ledsuitecama/Scheme"
  state_value_template: "{{ value }}"
  brightness_value_template: "{{ value }}"
  effect_value_template: "{{ value }}"
  retain: false
  qos: 1
  availability_topic: "tele/ledsuitecama/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "ledsuitetv"
  effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
  state_topic: "stat/ledsuitetv/POWER"
  command_topic: "cmnd/ledsuitetv/POWER"
  brightness_state_topic: "cmnd/ledsuitetv/Dimmer"
  brightness_command_topic: "cmnd/ledsuitetv/Dimmer"
  brightness_scale: 100
  rgb_state_topic: "cmnd/ledsuitetv/Color"
  rgb_command_topic: "cmnd/ledsuitetv/Color"
  effect_command_topic: "cmnd/ledsuitetv/Scheme"
  effect_state_topic: "cmnd/ledsuitetv/Scheme"
  state_value_template: "{{ value }}"
  brightness_value_template: "{{ value }}"
  effect_value_template: "{{ value }}"
  retain: false
  qos: 1
  availability_topic: "tele/ledsuitetv/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "ledquartotv"
  effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
  state_topic: "stat/ledquartotv/POWER"
  command_topic: "cmnd/ledquartotv/POWER"
  brightness_state_topic: "cmnd/ledquartotv/Dimmer"
  brightness_command_topic: "cmnd/ledquartotv/Dimmer"
  brightness_scale: 100
  rgb_state_topic: "cmnd/ledquartotv/Color"
  rgb_command_topic: "cmnd/ledquartotv/Color"
  effect_command_topic: "cmnd/ledquartotv/Scheme"
  effect_state_topic: "cmnd/ledquartotv/Scheme"
  state_value_template: "{{ value }}"
  brightness_value_template: "{{ value }}"
  effect_value_template: "{{ value }}"
  retain: false
  qos: 1
  availability_topic: "tele/ledquartotv/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "ledcozinhabalcao"
  effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
  state_topic: "stat/ledcozinhabalcao/POWER"
  command_topic: "cmnd/ledcozinhabalcao/POWER"
  brightness_state_topic: "cmnd/ledcozinhabalcao/Dimmer"
  brightness_command_topic: "cmnd/ledcozinhabalcao/Dimmer"
  brightness_scale: 100
  rgb_state_topic: "cmnd/ledcozinhabalcao/Color"
  rgb_command_topic: "cmnd/ledcozinhabalcao/Color"
  effect_command_topic: "cmnd/ledcozinhabalcao/Scheme"
  effect_state_topic: "cmnd/ledcozinhabalcao/Scheme"
  state_value_template: "{{ value }}"
  brightness_value_template: "{{ value }}"
  effect_value_template: "{{ value }}"
  retain: false
  qos: 1
  availability_topic: "tele/ledcozinhabalcao/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "ledchaocozinha"
  effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
  state_topic: "stat/ledchaocozinha/POWER"
  command_topic: "cmnd/ledchaocozinha/POWER"
  brightness_state_topic: "cmnd/ledchaocozinha/Dimmer"
  brightness_command_topic: "cmnd/ledchaocozinha/Dimmer"
  brightness_scale: 100
  rgb_state_topic: "cmnd/ledchaocozinha/Color"
  rgb_command_topic: "cmnd/ledchaocozinha/Color"
  effect_command_topic: "cmnd/ledchaocozinha/Scheme"
  effect_state_topic: "cmnd/ledchaocozinha/Scheme"
  state_value_template: "{{ value }}"
  brightness_value_template: "{{ value }}"
  effect_value_template: "{{ value }}"
  retain: false
  qos: 1
  availability_topic: "tele/ledchaocozinha/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: flux_led
  devices:
    192.168.1.30:
      name: ledsalatv
      mode: "rgb"
    192.168.1.31:
      name: ledsaladesktop
      mode: "rgb"

#MuvRH

- platform: mqtt
  name: "muv203entrada"
  command_topic: "cmnd/muv203entrada/POWER"
  state_topic: "stat/muv203entrada/POWER"
  availability_topic: "tele/muv203entrada/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "muv203banheiro"
  command_topic: "cmnd/muv203banheiro/POWER"
  state_topic: "stat/muv203banheiro/POWER"
  availability_topic: "tele/muv203banheiro/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "muv203operacoes"
  command_topic: "cmnd/muv203operacoes/POWER"
  state_topic: "stat/muv203operacoes/POWER"
  availability_topic: "tele/muv203operacoes/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "muv203nossasala"
  command_topic: "cmnd/muv203nossasala/POWER"
  state_topic: "stat/muv203nossasala/POWER"
  availability_topic: "tele/muv203nossasala/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "muv303entrada"
  command_topic: "cmnd/muv303entrada/POWER"
  state_topic: "stat/muv303entrada/POWER"
  availability_topic: "tele/muv303entrada/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "muv303banheiro"
  command_topic: "cmnd/muv303banheiro/POWER"
  state_topic: "stat/muv303banheiro/POWER"
  availability_topic: "tele/muv303banheiro/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "muv303dinamica"
  command_topic: "cmnd/muv303dinamica/POWER"
  state_topic: "stat/muv303dinamica/POWER"
  availability_topic: "tele/muv303dinamica/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "muv303corredor"
  command_topic: "cmnd/muv303corredor/POWER"
  state_topic: "stat/muv303corredor/POWER"
  availability_topic: "tele/muv303corredor/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "303leddinamica"
  effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
  state_topic: "stat/303leddinamica/POWER"
  command_topic: "cmnd/303leddinamica/POWER"
  brightness_state_topic: "cmnd/303leddinamica/Dimmer"
  brightness_command_topic: "cmnd/303leddinamica/Dimmer"
  brightness_scale: 100
  rgb_state_topic: "cmnd/303leddinamica/Color"
  rgb_command_topic: "cmnd/303leddinamica/Color"
  effect_command_topic: "cmnd/303leddinamica/Scheme"
  effect_state_topic: "cmnd/303leddinamica/Scheme"
  state_value_template: "{{ value }}"
  brightness_value_template: "{{ value }}"
  effect_value_template: "{{ value }}"
  retain: false
  qos: 1
  availability_topic: "tele/303leddinamica/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: template
  lights:
    ledsalatv_colorloop:
      friendly_name: "Led da TV da sala"
      icon_template: mdi:led-strip
      turn_on:
        service: script.ledsalatv_ligar_colorloop
      turn_off:
        service: light.turn_off
        data:
          entity_id: light.ledsalatv

#Grupos de luzes

- platform: group
  name: Luzes principais sala
  entities:
    - light.ledsalatv
    - light.ledsaladesktop

- platform: group
  name: Luzes principais cozinha
  entities:
    - light.cozinha
    - light.ledcozinhabalcao
    - light.ledchaocozinha

- platform: group
  name: Todas as luzes cozinha
  entities:
    - light.cozinha
    - light.ledcozinhabalcao
    - light.ledchaocozinha
    - light.area_servico

- platform: group
  name: Luzes principais quarto
  entities:
    - light.ledquartotv
    - light.quarto

- platform: group
  name: Todas as luzes suíte
  entities:
    - light.suite_principal
    - light.ledsuitetv
    - light.ledsuitecama

- platform: group
  name: Todos os leds suíte
  entities:
    - light.ledsuitetv
    - light.ledsuitecama

- platform: group
  name: Tudo banheiro suíte
  entities:
    - light.suite_banheiro_principal
    - light.suite_banheiro_espelho

- platform: group
  name: Tudo banheiro social
  entities:
    - light.banheiro_social_principal
    - light.banheiro_social_espelho
