- platform: webostv
  host: 192.168.1.39
  name: "TV Sala"
  filename: webostv2.conf
  turn_on_action:
    service: script.tv_lg_sala_power_on
  timeout: 60
  customize:
    sources:
      - hdmi1
      - hdmi2
      - hdmi3
      - livetv
      - youtube
      - netflix

- platform: webostv
  host: 192.168.1.38
  name: "TV Suíte"
  filename: webostv1.conf
  turn_on_action:
    service: script.tv_lg_suite_power_on
  timeout: 60
  customize:
    sources:
      - hdmi1
      - hdmi2
      - hdmi3
      - livetv
      - youtube
      - netflix

#- platform: lg_netcast
#  host: 192.168.1.40
#  access_token: 459689
#  name: 'TV Quarto'

#- platform: cast
#  host: 192.168.1.71
#
#- platform: cast
#  host: 192.168.1.60
#
#- platform: cast
#  host: 192.168.1.91