- platform: webostv
  host: 192.168.1.39
  name: "TV Sala"
  filename: webostv2.conf
  turn_on_action:
    service: script.tv_lg_sala_power_on
  timeout: 30
  customize:
    sources:
      - hdmi1
      - hdmi2
      - hdmi3
      - livetv
      - youtube
      - netflix

- platform: webostv
  host: 192.168.1.38
  name: "TV Suíte"
  filename: webostv1.conf
  turn_on_action:
    service: script.tv_lg_suite_power_on
  timeout: 30
  customize:
    sources:
      - hdmi1
      - hdmi2
      - hdmi3
      - livetv
      - youtube
      - netflix

- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
  name: "Spotify Casa"

- platform: lg_netcast
  host: 192.168.1.40
  access_token: 459689
  name: 'TV Quarto'
