- platform: wunderground
  api_key: !secret wunderground_api_key
  monitored_conditions:
    - weather_1h
  lang: BR

- platform: darksky
  api_key: !secret darksky_api_key
  language: pt
  forecast:
    - 1
  update_interval: 600
  monitored_conditions:
    - summary
    - temperature
    - temperature_low
    - temperature_high
    - humidity
    - precip_probability
    - daily_summary
    - minutely_summary
    - cloud_cover

- platform: broadlink
  update_interval: 300
  name: MuvRH
  host: 192.168.1.35
  mac: '34:EA:34:E4:5F:2F'
  monitored_conditions:
    - temperature

- platform: fastdotcom
  hour:
    - 1
    - 6
    - 13
    - 20

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: disk_use_percent
      arg: /home
    - type: memory_use_percent
    - type: since_last_boot

- platform: command_line
  name: CPU Temperature
  command: 'cat /sys/class/thermal/thermal_zone0/temp'
  unit_of_measurement: '°C'
  value_template: '{{ value | multiply(0.001) | round (1) }}'

- platform: template
  sensors:
    temperatura_real_nossa_sala:
      friendly_name: 'Temperatura real da nossa sala'
      unit_of_measurement: '°C'
      value_template: "{{ (states.sensor.muvrh_temperature.state  | float) - 2 }}"

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'
