#- platform: wunderground
#  api_key: !secret wunderground_api_key
#  monitored_conditions:
#    - weather_1h
#  lang: BR

- platform: darksky
  api_key: !secret darksky_api_key
  language: pt
  forecast:
    - 0
    - 1
  scan_interval: '05:00'
  monitored_conditions:
    - summary
    - temperature
    - temperature_low
    - temperature_high
    - humidity
    - precip_probability
    - daily_summary
    - minutely_summary
    - cloud_cover

- platform: uptime
  name: Dias funcionando
  unit_of_measurement: days

- platform: broadlink
  scan_interval: '00:30'
  name: MuvRH
  host: 192.168.1.35
  mac: '34:EA:34:E4:5F:2F'
  monitored_conditions:
    - temperature

- platform: fastdotcom
  hour:
    - 1
    - 6
    - 13
    - 20

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: disk_use_percent
      arg: /home
    - type: memory_use_percent

- platform: command_line
  name: CPU Temperature
  command: 'cat /sys/class/thermal/thermal_zone0/temp'
  unit_of_measurement: '°C'
  value_template: '{{ value | multiply(0.001) | round (1) }}'

- platform: template
  sensors:
    temperatura_real_nossa_sala:
      friendly_name: 'Temperatura real da nossa sala'
      entity_id: sensor.muvrh_temperature
      unit_of_measurement: '°C'
      value_template: "{{ (states.sensor.muvrh_temperature.state  | float) - 4 }}"

#    caixa_som_livre:
#      friendly_name: 'Caixa de som livre'
#      value_template: >-
#        {% if is_state('media_player.casa_inteira' , 'playing') %}
#          {% set speakers = ['media_player.banheiro_social', 'media_player.banheiro_suite',  'media_player.cozinha', 'media_player.quarto', 'media_player.sala', 'media_player.suite'] %}
#              {{ states.media_player | selectattr('entity_id', 'in', speakers) | selectattr('state','eq','off') | map(attribute='entity_id') | join(', ') }}
#        {% else %}
#          media_player.casa_inteira
#        {% endif %}


- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'

#- platform: qbittorrent
#  name: "qBittorrent Servidor"
#  url: 'http://192.168.1.10:7894'
#  username: !secret qbtitorrent_user
#  password: !secret qbtitorrent_password